/** Fabric physics presets — see section 10 of the product spec. Values are 0-1 normalized unless noted. */
export const FABRIC_PRESETS = [
  {
    name: "Cotton",
    massGsm: 180,
    friction: 0.45,
    stiffness: 0.35,
    bendingResistance: 0.4,
    stretchResistance: 0.3,
    damping: 0.3,
    elasticity: 0.25,
    drape: "medium",
    breathability: "high",
  },
  {
    name: "Silk",
    massGsm: 60,
    friction: 0.15,
    stiffness: 0.1,
    bendingResistance: 0.12,
    stretchResistance: 0.15,
    damping: 0.15,
    elasticity: 0.2,
    drape: "high",
    breathability: "medium",
  },
  {
    name: "Denim",
    massGsm: 420,
    friction: 0.6,
    stiffness: 0.75,
    bendingResistance: 0.8,
    stretchResistance: 0.6,
    damping: 0.5,
    elasticity: 0.1,
    drape: "low",
    breathability: "low",
  },
  {
    name: "Wool",
    massGsm: 300,
    friction: 0.5,
    stiffness: 0.5,
    bendingResistance: 0.55,
    stretchResistance: 0.4,
    damping: 0.45,
    elasticity: 0.3,
    drape: "medium",
    breathability: "medium",
  },
  {
    name: "Leather",
    massGsm: 550,
    friction: 0.7,
    stiffness: 0.9,
    bendingResistance: 0.85,
    stretchResistance: 0.85,
    damping: 0.6,
    elasticity: 0.05,
    drape: "low",
    breathability: "low",
  },
  {
    name: "Linen",
    massGsm: 200,
    friction: 0.4,
    stiffness: 0.4,
    bendingResistance: 0.45,
    stretchResistance: 0.35,
    damping: 0.35,
    elasticity: 0.15,
    drape: "medium",
    breathability: "high",
  },
] as const;
